Parameterized xml, inc, vrt and cfg files. Moved all source files to their own directory.

diff --git a/script/process_sources b/script/process_sources
--- a/script/process_sources
+++ b/script/process_sources
@@ -1,12 +1,18 @@
 #!/bin/bash
 
-# Generates the mapnik style files and includes from
-# their respective carto templates.
+# Generates the mapnik style files, includes etc from
+# their respective sources.
 
 # Variable declarations on the form ${VAR} are substituted with
 # the value of the corresponding enviroment variable VAR.
 
-SOURCEDIR="carto"
+if [[ -z $TOPOSM_ENV_SET ]]; then
+    echo "Error: TopOSM environment not set."
+    exit 1
+fi
+
+
+SOURCEDIR="sources"
 DESTDIR="processed"
 
 # awk program to substitute environment variables
@@ -18,13 +24,9 @@ AWKFILTER='{while(match($0,"[$]{[^}]*}")){var=substr($0,RSTART+2,RLENGTH -3);gsu
 MILLSTONEFILTER="\[millstone\]"
 
 
-if [[ -z $TOPOSM_ENV_SET ]]; then
-    echo "Error: TopOSM environment not set."
-    exit 1
-fi
-
-# Generate mapnik XML from Carto templates
 mkdir -pv "$DESTDIR"
+
+# Generate Mapnik XML from Carto templates
 for SRC in `ls ${SOURCEDIR}/*.mml`; do
     echo "Processing $SRC..."
     DST="${DESTDIR}/`basename $SRC .mml`.xml"
@@ -37,7 +39,13 @@ for SRC in `ls ${SOURCEDIR}/*.mml`; do
     # read errors from output file
     # (carto writes these to stdout and always returns 0)
     cat $DST | grep "carto:"
-        
+done
+
+# Process xml,inc,vrt,cfg files
+for SRC in `ls ${SOURCEDIR}/*.{xml,inc,vrt,cfg}`; do
+    echo "Processing $SRC..."
+    DST="${DESTDIR}/`basename $SRC`"        
+    cat $SRC | awk "$AWKFILTER" > $DST
 done
 
 echo "Done."
